from HardwareMonitor._util.types import UInt32


class MsiDevice:
    def __init__(self, msiDeviceType: MsiDeviceType, vendorId: int, productId: int, productIdController: int): ...
    @property
    def DeviceType(self) -> MsiDeviceType: ...
    @property
    def Name(self) -> str: ...
    @property
    def ProductId(self) -> int: ...
    @property
    def ProductIdController(self) -> int: ...
    @property
    def VendorId(self) -> int: ...
    def SupportsHWMonitorIndex13and14(self, firmwareVersion: UInt32) -> bool: ...


class MsiDeviceType:
    S280 = 0
    S360 = 1
    S360MEG = 2
    X360 = 3
    X240 = 4
    D360 = 5
    D240 = 6


class MsiFan:
    def __init__(self): ...
    @property
    def Duty(self) -> int: ...
    @property
    def Speed(self) -> int: ...
    @Duty.setter
    def Duty(self, value: int) -> None: ...
    @Speed.setter
    def Speed(self, value: int) -> None: ...


class MsiFanConfigure:
    def __init__(self): ...


class MsiFanControl:
    def __init__(self): ...
    @property
    def Fan1(self) -> MsiFan: ...
    @property
    def Fan2(self) -> MsiFan: ...
    @property
    def Fan3(self) -> MsiFan: ...
    @property
    def Fan4(self) -> MsiFan: ...
    @property
    def Fan5(self) -> MsiFan: ...
    @property
    def TemperatureInlet(self) -> int: ...
    @property
    def TemperatureOutlet(self) -> int: ...
    @property
    def TemperatureSensor1(self) -> int: ...
    @property
    def TemperatureSensor2(self) -> int: ...
    @Fan1.setter
    def Fan1(self, value: MsiFan) -> None: ...
    @Fan2.setter
    def Fan2(self, value: MsiFan) -> None: ...
    @Fan3.setter
    def Fan3(self, value: MsiFan) -> None: ...
    @Fan4.setter
    def Fan4(self, value: MsiFan) -> None: ...
    @Fan5.setter
    def Fan5(self, value: MsiFan) -> None: ...
    @TemperatureInlet.setter
    def TemperatureInlet(self, value: int) -> None: ...
    @TemperatureOutlet.setter
    def TemperatureOutlet(self, value: int) -> None: ...
    @TemperatureSensor1.setter
    def TemperatureSensor1(self, value: int) -> None: ...
    @TemperatureSensor2.setter
    def TemperatureSensor2(self, value: int) -> None: ...


class MsiFanMode:
    Silent = 0
    Bios = 1
    Game = 2
    Custom = 3
    Unknown = 4
    Smart = 5
