from HardwareMonitor._util.types import Nullable
from typing import List


class WireViewPro2(Hardware):
    def __init__(self, portName: str, settings: ISettings, baud: int): ...
    def ClearFaults(self, faultStatusMask: int, faultLogMask: int) -> None: ...
    def Close(self) -> None: ...
    @property
    def ConfigVersion(self) -> int: ...
    @property
    def HardwareType(self) -> HardwareType: ...
    @property
    def IsConnected(self) -> bool: ...
    @property
    def UniqueID(self) -> str: ...
    @property
    def VendorData(self) -> Nullable: ...
    def GetDeviceData(self) -> DeviceData: ...
    def GetReport(self) -> str: ...
    def NonVolatileMemoryCommand(self, cmd: NVM_CMD) -> None: ...
    def ReadConfig(self) -> Nullable: ...
    def ScreenCmd(self, cmd: SCREEN_CMD) -> None: ...
    def TryFindDevices(settings: ISettings) -> List: ...
    def Update(self) -> None: ...
    def WriteConfig(self, config: DeviceConfigStructV3) -> None: ...
