from HardwareMonitor._util.types import Byte, IReadOnlyList, Nullable, Single, TimeSpan


class ISmart:
    @property
    def Attributes(self) -> IReadOnlyList: ...


class SmartAttribute:
    def __init__(self, smartAttribute: SmartAttributeEntry, sensorType: Nullable, sensorChannel: int, sensorName: str, defaultHiddenSensor: bool): ...
    @property
    def Attribute(self) -> SmartAttributeEntry: ...
    @property
    def Id(self) -> Byte: ...
    @property
    def IsHiddenByDefault(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @property
    def SensorChannel(self) -> int: ...
    @property
    def SensorName(self) -> str: ...
    @property
    def SensorType(self) -> Nullable: ...
    @property
    def Threshold(self) -> Byte: ...
    @property
    def Value(self) -> Single: ...


class StorageDevice(Hardware):
    def __init__(self, storage: StorageDevice, settings: ISettings): ...
    @property
    def Attributes(self) -> IReadOnlyList: ...
    @property
    def ForceWakeup(self) -> bool: ...
    @property
    def HardwareType(self) -> HardwareType: ...
    @property
    def Storage(self) -> StorageDevice: ...
    @property
    def ThrottleInterval() -> TimeSpan: ...
    def GetReport(self) -> str: ...
    @ForceWakeup.setter
    def ForceWakeup(self, value: bool) -> None: ...
    @ThrottleInterval.setter
    def ThrottleInterval(value: TimeSpan) -> None: ...
    def Traverse(self, visitor: IVisitor) -> None: ...
    def Update(self) -> None: ...
