from HardwareMonitor._util.types import IReadOnlyList


class CorsairPsuGroup:
    def __init__(self, settings: ISettings): ...
    def Close(self) -> None: ...
    @property
    def Hardware(self) -> IReadOnlyList: ...
    def GetReport(self) -> str: ...
