from HardwareMonitor.Hardware import ISettings
from HardwareMonitor._util.types import IReadOnlyList


class CommunicationProtocolError:
    def __init__(self, device: HidDevice, message: str): ...


class CorsairPsuGroup:
    def __init__(self, settings: ISettings): ...
    def Close(self) -> None: ...
    @property
    def Hardware(self) -> IReadOnlyList: ...
    def GetReport(self) -> str: ...
